name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - "GuildWarsPartySearch.Common/**"
      - "GuildWarsPartySearch/**"
      - ".github/workflows/docker-deploy.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Log in to Docker Hub
      run: |
        docker login guildwarspartysearch.azurecr.io --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_PASSWORD }}"

    - name: Set secrets in Web App
      shell: pwsh
      run: |
        az login --service-principal --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
        az webapp config appsettings set --name guildwarspartysearch --resource-group GuildWarsPartySearch --settings ServerOptions:ApiKey=${{ secrets.APIKEY }}
        az webapp config appsettings set --name guildwarspartysearch --resource-group GuildWarsPartySearch --settings ServerOptions:Certificate=${{ secrets.CERTIFICATE_BASE64 }}
        az webapp config appsettings set --name guildwarspartysearch --resource-group GuildWarsPartySearch --settings ApplicationInsights:InstrumentationKey=${{ secrets.AZURE_INSIGHTS_INSTRUMENTATIONKEY }}
        az webapp config appsettings set --name guildwarspartysearch --resource-group GuildWarsPartySearch --settings AzureCredentialsOptions:ClientSecret=${{ secrets.AZURE_CLIENT_SECRET }}
        az webapp config appsettings set --name guildwarspartysearch --resource-group GuildWarsPartySearch --settings AzureCredentialsOptions:ClientId=${{ secrets.AZURE_CLIENT_ID }}
        az webapp config appsettings set --name guildwarspartysearch --resource-group GuildWarsPartySearch --settings AzureCredentialsOptions:TenantId=${{ secrets.AZURE_TENANT_ID }}
        Write-Host "Secrets placed in Web App"

    - name: Build and push Docker image
      run: |
        cd GuildWarsPartySearch
        .\BuildDockerImage.ps1
        docker push guildwarspartysearch.azurecr.io/guildwarspartysearch.server
      shell: pwsh