name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - "GuildWarsPartySearch.Common/**"
      - "GuildWarsPartySearch/**"
      - ".github/workflows/docker-deploy.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    # - name: Create Docker Environment File
    #   shell: pwsh
    #   run: |
    #     cd GuildWarsPartySearch
    #     $envFilePath = "envfile"
    #     $envContent = @(
    #         "ApplicationInsights__InstrumentationKey=${{ secrets.AZURE_INSIGHTS_INSTRUMENTATIONKEY }}",
    #         "AzureCredentialsOptions__ClientSecret=${{ secrets.AZURE_CLIENT_SECRET }}",
    #         "AzureCredentialsOptions__ClientId=${{ secrets.AZURE_CLIENT_ID }}",
    #         "AzureCredentialsOptions__TenantId=${{ secrets.AZURE_TENANT_ID }}"
    #     )
    #     $envContent | Set-Content -Path $envFilePath
    #     Write-Host "Environment file created: $envFilePath"

    - name: Build server
      run: |
        dotnet publish .\GuildWarsPartySearch\GuildWarsPartySearch.Server.csproj -c Release -r linux-x64 -o .\GuildWarsPartySearch\Publish\
        Copy-Item -Path .\GuildWarsPartySearch\Config.Release.json -Destination GuildWarsPartySearch\Publish\Config.json
      shell: pwsh

    - name: Replace secrets in configuration
      shell: pwsh
      run: |
        $jsonContent = Get-Content -Raw -Path GuildWarsPartySearch\Publish\Config.json | ConvertFrom-Json
        $jsonContent.ApplicationInsights.InstrumentationKey = "${{ secrets.AZURE_INSIGHTS_INSTRUMENTATIONKEY }}"
        $jsonContent.AzureCredentialsOptions.ClientSecret = "${{ secrets.AZURE_CLIENT_SECRET }}"
        $jsonContent.AzureCredentialsOptions.ClientId = "${{ secrets.AZURE_CLIENT_ID }}"
        $jsonContent.AzureCredentialsOptions.TenantId = "${{ secrets.AZURE_TENANT_ID }}"
        $updatedJsonContent = $jsonContent | ConvertTo-Json -Depth 32
        Set-Content -Path GuildWarsPartySearch\Publish\Config.json -Value $updatedJsonContent

    - name: Build docker image
      run: |
        cd GuildWarsPartySearch
        docker build -t guildwarspartysearch.server .
        cd ..
        docker save -o guildwarspartysearch.server.tar guildwarspartysearch.server
        echo 

    - name: Deploy Docker image to host
      shell: pwsh
      run: |
        sshpass -p ${{ secrets.HOST_PASS }} scp guildwarspartysearch.server.tar ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDRESS }}:/staging/